apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: k8s-multi-club-tls
spec:
  secretName: k8s-multi-club
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-multi.club
  dnsNames:
    - k8s-multi.club
    - www.k8s-multi.club